name: Build Release
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm install
    # - run: npm test
    - run: npm run prebuild
    # - run: npm run upload:electron
    # Moved to release-action

    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "prebuilds/@ffxiv-teamcraft/*"
        tag: 0.0.13
        allowUpdates: true
        replacesArtifacts: true
        skipIfReleaseExists: false
      
    # - name: Archive production artifacts
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: build-artifacts
    #     path: build/**

    - name: Save Builds
      uses: actions/upload-artifact@v4
      with:
        name: prebuilds
        path: prebuilds/@ffxiv-teamcraft/**