name: Publish to NPM
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

      # - name: Publish package on NPM 📦
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  build:

    runs-on: windows-latest
    # env:
    #   PREBUILD_GH_TOKEN: ${{ secrets.PREBUILD_GH_TOKEN }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    # - run: npm test
    - run: npm run prebuild
    # - run: npm run upload:electron

    - name: Create Release
      uses: ncipollo/release-action@v1
      with: 
        artifacts: "prebuilds/@ffxiv-teamcraft/**"
        tag: 0.0.13
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/**

    - name: Save Builds
      uses: actions/upload-artifact@v4
      with:
        name: prebuilds
        path: prebuilds/@ffxiv-teamcraft/**